name: Verify

on:
  push:
    branches:
      - "**"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build (utils)
        working-directory: packages/utils
        run: yarn build

      - name: Typecheck (utils)
        working-directory: packages/utils
        run: yarn typecheck

      - name: Lint (utils)
        working-directory: packages/utils
        run: yarn lint

      - name: Test (utils)
        working-directory: packages/utils
        run: yarn test

      - name: Build (cli)
        working-directory: packages/cli
        run: yarn build

      - name: Reinstall
        run: |
          find . -name node_modules | xargs rm -rf
          yarn

      - name: Typecheck (cli)
        working-directory: packages/cli
        run: yarn typecheck

      - name: Lint (cli)
        working-directory: packages/cli
        run: yarn lint

      - name: Test (cli)
        working-directory: packages/cli
        run: yarn test

      - name: E2e test
        working-directory: packages/private/e2e-tests
        run: yarn test
